### ISSUE TITLE
Martens EventStore

### ISSUE THREAD

**Issue by Silv3rcircl3** [raskolnikoov/Akka.Persistence.Marten#1]
Hi, 

one question, why haven't you used Marten's EventStore functionality ?
This would allow one to use Marten's projection API in combination with Akka.Persistence.

Cheers Marc

**Comment by raskolnikoov** [comment]
Hi Marc, I have no good answer to that besides I dident think about it. Feel free to make a pull request with the changes needed. :)

**Comment by Silv3rcircl3** [comment]
I think I know why :) Currently marten doesn't support snapshots. I'll recheck once this functionality is available.
